# Generated by Django 5.0.4 on 2024-08-03 16:35

from django.db import migrations, connection
from django.db import connections as djcs
from explorer import app_settings


def from_django_connection(apps, connection_alias):
    DatabaseConnection = apps.get_model('explorer', 'DatabaseConnection')
    return DatabaseConnection(
        alias=connection_alias,
        name=connection_alias,
        engine="django_connection"
    )


def populate_new_foreign_key(apps, _):
    DatabaseConnection = apps.get_model('explorer', 'DatabaseConnection')

    # Create new connection for each based on EXPLORER_CONNECTIONS
    connections = [c for c in djcs if c in app_settings.EXPLORER_CONNECTIONS.values()]
    for c in connections:
        if not DatabaseConnection.objects.filter(alias=c).exists():
            obj = from_django_connection(apps, c)
            obj.save()
            print(f"created Connection ID {obj.id} for {obj.alias}")

    with connection.cursor() as cursor:
        for c in DatabaseConnection.objects.all():
            # Update Query table
            cursor.execute("""
                UPDATE explorer_query
                SET database_connection_id = %s
                WHERE connection = %s
            """, [c.id, c.alias])

            # Update QueryLog table
            cursor.execute("""
                UPDATE explorer_querylog
                SET database_connection_id = %s
                WHERE connection = %s
            """, [c.id, c.alias])


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0023_query_database_connection_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_new_foreign_key),
    ]
